REGLAS_PREGRADO = [
    ("ECONOM", "FINANZAS_BANCA", 40),
    ("ECONOM", "ANALITICA_DATOS", 35),
    ("ECONOM", "MBA_ADMINISTRACION", 25),

    ("ADMIN", "MBA_ADMINISTRACION", 40),
    ("ADMIN", "FINANZAS_BANCA", 30),
    ("ADMIN", "MARKETING_COMERCIAL", 25),
    ("ADMIN", "GESTION_PROYECTOS", 25),

    ("DERECHO", "DERECHO_LEGAL", 40),
    ("DERECHO", "MBA_ADMINISTRACION", 20),

    ("INGENIER", "TECNOLOGIA", 30),
    ("INGENIER", "ANALITICA_DATOS", 35),
    ("INGENIER", "GESTION_PROYECTOS", 30),
    ("INGENIER", "MBA_ADMINISTRACION", 20),

    ("MEDIC", "SALUD_GESTION", 40),
    ("ENFERM", "SALUD_GESTION", 40),
    ("ODONTO", "SALUD_GESTION", 40),
    ("FISIOTER", "SALUD_GESTION", 40),
    ("VETERIN", "SALUD_GESTION", 30),

    ("PSICO", "PSICOLOGIA_RRHH", 40),
    ("PSICO", "MBA_ADMINISTRACION", 20),

    ("MARKETING", "MARKETING_COMERCIAL", 40),
    ("PUBLICIDAD", "MARKETING_COMERCIAL", 35),

    ("ARQUIT", "ARQUITECTURA_DISENO", 40),
    ("DISENO", "ARQUITECTURA_DISENO", 40),
    ("DISEÑO", "ARQUITECTURA_DISENO", 40),

    ("EDUC", "EDUCACION", 40),

    ("GASTRO", "MBA_ADMINISTRACION", 25),
    ("NEGOCIOS", "MBA_ADMINISTRACION", 35),
    ("COMERCIO", "MARKETING_COMERCIAL", 25),
]


REGLAS_SECTOR = [
    ("BANCO", "FINANZAS_BANCA", 25),
    ("FINANCIERA", "FINANZAS_BANCA", 25),
    ("COOPERATIVA", "FINANZAS_BANCA", 20),
    ("SEGUROS", "FINANZAS_BANCA", 20),

    ("HOSPITAL", "SALUD_GESTION", 25),
    ("CLINICA", "SALUD_GESTION", 25),
    ("SALUD", "SALUD_GESTION", 20),

    ("UNIVERSIDAD", "EDUCACION", 25),
    ("COLEGIO", "EDUCACION", 25),
    ("INSTITUTO", "EDUCACION", 20),

    ("SOFTWARE", "TECNOLOGIA", 25),
    ("TECNOLOG", "TECNOLOGIA", 20),
    ("SISTEMAS", "TECNOLOGIA", 20),

    ("MINISTERIO", "MBA_ADMINISTRACION", 15),
    ("GOBIERNO", "MBA_ADMINISTRACION", 15),
    ("DIRECCION DISTRITAL", "MBA_ADMINISTRACION", 15),
    ("FUNCION EJECUTIVA", "MBA_ADMINISTRACION", 15),

    ("COMERCIAL", "MARKETING_COMERCIAL", 20),
    ("VENTAS", "MARKETING_COMERCIAL", 20),
]


REGLAS_CARGO = [
    ("ANALISTA", "ANALITICA_DATOS", 25),
    ("ANALISTA", "FINANZAS_BANCA", 15),

    ("FINANCI", "FINANZAS_BANCA", 25),
    ("RIESGO", "FINANZAS_BANCA", 25),
    ("CREDITO", "FINANZAS_BANCA", 25),
    ("CRÉDITO", "FINANZAS_BANCA", 25),
    ("CONTAB", "FINANZAS_BANCA", 20),
    ("AUDIT", "FINANZAS_BANCA", 20),

    ("PROGRAMADOR", "TECNOLOGIA", 25),
    ("DESARROLLADOR", "TECNOLOGIA", 25),
    ("SOFTWARE", "TECNOLOGIA", 25),
    ("DATOS", "ANALITICA_DATOS", 25),

    ("MEDICO", "SALUD_GESTION", 25),
    ("MÉDICO", "SALUD_GESTION", 25),
    ("MEDICA", "SALUD_GESTION", 25),
    ("MÉDICA", "SALUD_GESTION", 25),
    ("ENFERM", "SALUD_GESTION", 25),
    ("ODONTO", "SALUD_GESTION", 25),

    ("JURID", "DERECHO_LEGAL", 25),
    ("JURÍD", "DERECHO_LEGAL", 25),
    ("LEGAL", "DERECHO_LEGAL", 25),
    ("ABOG", "DERECHO_LEGAL", 25),

    ("JEFE", "MBA_ADMINISTRACION", 25),
    ("GERENTE", "MBA_ADMINISTRACION", 25),
    ("COORDINADOR", "MBA_ADMINISTRACION", 20),
    ("SUPERVISOR", "MBA_ADMINISTRACION", 20),
    ("DIRECTOR", "MBA_ADMINISTRACION", 25),

    ("PROYECT", "GESTION_PROYECTOS", 25),

    ("COMERCIAL", "MARKETING_COMERCIAL", 25),
    ("VENTAS", "MARKETING_COMERCIAL", 25),
    ("MARKETING", "MARKETING_COMERCIAL", 25),

    ("DOCENTE", "EDUCACION", 25),
    ("PROFESOR", "EDUCACION", 25),
]
